Enhanced_SCRPA_Data
// ================================================================
// SCRPA Enhanced Data Loader - Optimized M Code
// ================================================================
// Project: SCRPA_Time_v2 Power BI Integration
// Author: R. A. Carucci
// Purpose: High-performance CSV loader for Python-processed SCRPA data
// Last Updated: 2025-07-27
// Prerequisites: enhanced_scrpa_data.csv generated by master_scrpa_processor.py
// ================================================================

let
    FilePath = "C:\\Users\\carucci_r\\OneDrive - City of Hackensack\\01_DataSources\\SCRPA_Time_v2\\04_powerbi\\enhanced_scrpa_data.csv",
    Raw      = Csv.Document(File.Contents(FilePath), [Delimiter=",", Encoding=65001]),
    Promoted = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
    Typed    = Table.TransformColumnTypes(Promoted, {
        {"Case_Number", type text}, {"How Reported", type text}, {"FullAddress2", type text},
        {"PDZone", type text},                              // <-- CORRECTED data type to text
        {"Time of Call", type datetime}, {"Incident_DateTime", type datetime},
        {"IncidentType", type text}, {"ALL_INCIDENTS", type text}, {"Period", type text},
        {"Crime_Category", type text}, {"CAD_Username", type text}, {"CAD_Timestamp", type datetime},
        {"CAD_Notes_Cleaned", type text}, {"Time_Response_Minutes", type number},
        {"Response_Time_Formatted", type text}, {"Time_On_Scene_Minutes", type number},
        {"Time_On_Scene_Formatted", type text}, {"TimeOfDay", type text}
    }),
    Result   = Table.Buffer(Typed)
in
    Result

Case_Number	FullAddress2	How Reported	PDZone	Time of Call	Incident_Date	Incident_Time	Incident_DateTime	TimeOfDay	Enhanced_Block	Period	ALL_INCIDENTS	IncidentType	Crime_Category	Time_Response_Minutes	Response_Time_Formatted	Time_On_Scene_Minutes	Time_On_Scene_Formatted	CAD_Username	CAD_Timestamp	CAD_Notes_Cleaned
25-000813	309 Lookout Avenue, Hackensack, NJ, 07601	Phone	9	01/04/25 10:59:09			null	Unknown	Lookout Avenue, 300 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	13.46666667	13 Mins 28 Secs	-21.33333333	-1 Hrs 39 Mins	Kiselow_G	01/04/25 11:00:23	Taken out of driveway last night. Vehicle was located in clarkstown, ny. Involved in 69 last night ? ? ?
25-002564	135 First Street, Hackensack, NJ, 07601	Other - See Notes	7	01/10/25 14:20:51			null	Unknown	First Street, 100 Block	Historical	Criminal Sexual Contact - 2C:14-3a	Criminal Sexual Contact	Sexual Offenses	0.633333333	38 Secs	-0.033333333	0 Mins		null	
25-002635	90 Prospect Avenue, Hackensack, NJ, 07601	Phone		01/10/25 19:49:52			null	Unknown	Prospect Avenue, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	14.7	14 Mins 42 Secs	-50.56666667	-1 Hrs 10 Mins	Cavallo_F	01/10/25 19:57:11	Meet the complainant in the lobby, she is reporting that her company vehicle was broken into and tools were stolen from it. She believes it was her ex husband. ? ? ?
25-003806	133 Cedar Avenue, Hackensack, NJ, 07601	9-1-1	9	01/14/25 14:59:48			null	Unknown	Cedar Avenue, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	8.683333333	8 Mins 41 Secs	-31.4	-1 Hrs 29 Mins	Iannacone_A	01/14/25 15:02:06	Caller stating that her ex went into her home and took some items that were hers male party is no longer on scene. Unk when male party entered the residence. County cad 25 017062. Total proceeds $1,282
25-004097	244 First Street, Hackensack, NJ, 07601	Phone	8	01/15/25 12:57:26			null	Unknown	First Street, 200 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	1.783333333	1 Mins 47 Secs	-70.01666667	-2 Hrs 50 Mins		null	
25-004629	630 Main Street, Hackensack, NJ, 07601	Phone	9	01/17/25 12:16:59			null	Unknown	Main Street, 600 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	5.433333333	5 Mins 26 Secs	-12.43333333	-1 Hrs 48 Mins	Gervasi_J	01/17/25 12:22:23	Rep that it ocurred on 01/16/2025 @ 2115. Shoplifter assaulted security guard. ? ? ? ? ? ?
25-005871	33 Ross Avenue, Hackensack, NJ, 07601	9-1-1	9	01/22/25 3:10:53			null	Unknown	Ross Avenue, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	5.516666667	5 Mins 31 Secs	-86.81666667	-2 Hrs 34 Mins		null	
25-005972	170 South Park Street, Hackensack, NJ, 07601	Walk-In	7	01/22/25 11:51:55			null	Unknown	South Park Street, 100 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	16.95	16 Mins 57 Secs	-73.03333333	-2 Hrs 47 Mins		null	
25-006083	443 Hudson Street, Hackensack, NJ, 07601	Phone	5	01/22/25 19:14:56			null	Unknown	Hudson Street, 400 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	7	7 Mins	-95.6	-2 Hrs 25 Mins		null	
25-006463	208 Anderson Street, Hackensack, NJ, 07601	Phone	8	01/24/25 5:01:17			null	Unknown	Anderson Street, 200 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	2.783333333	2 Mins 47 Secs	-94.95	-2 Hrs 26 Mins	Ortiz_N	01/24/25 5:03:08	Caller reports she woke up with more clothes on then when she went to bed. As conversation progressed caller reported waking up with less clothes and sore vagina. ? ? ?
25-008053	140 Hudson Street, Hackensack, NJ, 07601	9-1-1	5	01/29/25 20:53:22			null	Unknown	Hudson Street, 100 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	1.1	1 Mins 06 Secs	-17.88333333	-1 Hrs 43 Mins	Scott_L	01/29/25 20:53:49	Female caller stated she has been raped stated the male party is still there she was unsure if there is an apartment number/letter caller disconnected.
25-008075	119 Essex Street, Hackensack, NJ, 07601	Phone	6	01/29/25 22:02:24			null	Unknown	Essex Street, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	2.116666667	2 Mins 07 Secs	-26.3	-1 Hrs 34 Mins	Swetits_M	01/29/25 22:04:14	See caller believes her vehicle was stolen...tow reports checked and were negative ? ? ? ? ? ?
25-008777	453 Sutton Avenue, Hackensack, NJ, 07601	9-1-1	6	02/01/25 2:52:33			null	Unknown	Sutton Avenue, 400 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	2.616666667	2 Mins 37 Secs	-138.0166667	-3 Hrs 42 Mins	Wouters_F	02/01/25 2:54:35	25 039344 ? ? ? ? ? ?
25-009348	144 Hudson Street, Hackensack, NJ, 07601	Radio	5	02/03/25 12:02:04			null	Unknown	Hudson Street, 100 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	0.45	27 Secs	-29.88333333	-1 Hrs 31 Mins	Gervasi_J	02/03/25 12:02:31	Flagged down by male party states he was robbed drone deployed. Provided overwatch. ? ? ?
25-009438	400 Hackensack Avenue, Hackensack, NJ, 07601	Phone	9	02/03/25 16:40:35			null	Unknown	Hackensack Avenue, 400 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	4.183333333	4 Mins 11 Secs	-89.68333333	-2 Hrs 31 Mins	Farhi_B	02/03/25 16:42:06	Actors are goa. Theft of 2 bags and pushed store employee to the floor as they fled. ? ? ? ? ? ?
25-009550	411 Simons Avenue, Hackensack, NJ, 07601	Phone	6	02/04/25 3:21:47			null	Unknown	Simons Avenue, 400 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	1.8	1 Mins 48 Secs	-11.48333333	-1 Hrs 49 Mins	Ortiz_N	02/04/25 3:23:11	Male party attempting to steal callers car fled towards summit last seen wearing blk hoodie, suspect heard callers dog bark and fled area bcc# 25 042959 ? ? ?
25-009657	55 Midtown Bridge Approach, Hackensack, NJ, 07601	Phone	8	02/04/25 12:43:32			null	Unknown	Midtown Bridge Approach, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	40.55	40 Mins 33 Secs	-67.43333333	-2 Hrs 53 Mins	Antista_Ma	02/04/25 12:44:03	Possible 26 ? ? ? ? ? ?
25-010474	170 Hudson Street, Hackensack, NJ, 07601	Phone	5	02/07/25 7:22:38			null	Unknown	Hudson Street, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	1.55	1 Mins 33 Secs	-63.28333333	-2 Hrs 57 Mins	Small_K	02/07/25 7:23:41	26, 05 dodge caravan, was left running in driveway ? ? ? ? ? ?
25-010788	Hudson Street & Moonachie Road, Hackensack, NJ, 07601	Walk-In	5	02/08/25 9:22:04			null	Unknown	Hudson Street & Moonachie Road	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	3.916666667	3 Mins 55 Secs	-56.25	-1 Hrs 04 Mins		null	
25-012325	280 Kipp Street, Hackensack, NJ, 07601	Phone	6	02/14/25 7:10:39			null	Unknown	Kipp Street, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	1.65	1 Mins 39 Secs	-18.58333333	-1 Hrs 42 Mins	Wouters_F	02/14/25 7:11:15	Pse& van ? ? ? ? ? ?
25-013091	100 Second Street, Hackensack, NJ, 07601	Walk-In	7	02/17/25 8:22:14			null	Unknown	Second Street, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	2.833333333	2 Mins 50 Secs	-60.3	-1 Hrs	Cavallo_F	02/17/25 8:25:31	Walk in, stolen auto, located in rochelle park with no wheels on it. Advise rochelle park once entered into ncic, ? ? ?
25-013527	240  Prospect Avenue, Hackensack, NJ, 07601	Phone	8	02/18/25 17:39:20			null	Unknown	Prospect Avenue, 200 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	0.383333333	23 Secs	-0.05	0 Mins	Dogali_M	02/18/25 17:40:25	Patient located at mt. Sinai er, responding with det. Tanucilli ? ? ? ? ? ?
25-013689	18 East Camden Street, Hackensack, NJ, 07601	Walk-In	8	02/19/25 9:17:12			null	Unknown	East Camden Street, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	2.95	2 Mins 57 Secs	-24.93333333	-1 Hrs 36 Mins	Cavallo_F	02/19/25 9:17:36	*****walk in***** ? ? ? ? ? ?
25-014007	360 Union Street, Hackensack, NJ, 07601	Phone	8	02/20/25 12:52:04			null	Unknown	Union Street, 300 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	11.4	11 Mins 24 Secs	-37.15	-1 Hrs 23 Mins	Briggs_S	02/20/25 12:52:29	See det. James ? ? ? ? ? ?
25-015290	430 Washington Avenue, Hackensack, NJ, 07601	9-1-1	5	02/24/25 23:47:34			null	Unknown	Washington Avenue, 400 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	3.5	3 Mins 30 Secs	-52.3	-1 Hrs 08 Mins	Sosa_C	02/24/25 23:48:44	Ccad# 25 069523 possible 26 ? ? ? ? ? ?
25-016142	100 State Street, Hackensack, NJ, 07601	Phone	7	02/27/25 21:22:35			null	Unknown	State Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	4.85	4 Mins 51 Secs	-44.11666667	-1 Hrs 16 Mins	Ortiz_N	02/27/25 21:23:50	Caller reports her door knob is hanging off the door and key fob is non functional ? ? ? ? ? ?
25-018160	216 Central Avenue, Hackensack, NJ, 07601	Phone	8	03/06/25 22:35:45			null	Unknown	Central Avenue, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	11.05	11 Mins 03 Secs	-30.58333333	-1 Hrs 30 Mins	Antista_Ma	03/06/25 22:36:22	See mike gibson in ref to 43 to his car ? ? ? ? ? ?
25-019111	65 Court Street, Hackensack, NJ, 07601	9-1-1	5	03/09/25 21:32:32			null	Unknown	Court Street, 0 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	1.683333333	1 Mins 41 Secs	-38.78333333	-1 Hrs 22 Mins	Scott_L	03/09/25 21:33:45	"Callers reporting he hears female party screaming ""im getting raped call 911"" behind pep boys ccad# 25 087241"
25-019245	282 American Legion Drive, Hackensack, NJ, 07601	Phone	7	03/10/25 8:53:28			null	Unknown	American Legion Drive, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	0	0 Secs	0	0 Mins	Kiselow_G	03/10/25 8:54:41	Silver hyundai. 2 door. Complainant standing with the vehicle ? ? ? ? ? ?
25-020998	472 Passaic Street, Hackensack, NJ, 07601	Phone	8	03/15/25 20:39:03			null	Unknown	Passaic Street, 400 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	12.93333333	12 Mins 56 Secs	-22.11666667	-1 Hrs 38 Mins	Cavallo_F	03/15/25 20:47:30	Complainant is reporting that noel smith stole box containing $3000 from her closet. No contact order in effect barring him from the property ? ? ?
25-021086	64 Prospect Avenue, Hackensack, NJ, 07601	9-1-1	7	03/16/25 3:15:35			null	Unknown	Prospect Avenue, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.333333333	3 Mins 20 Secs	-179.9666667	-3 Hrs 01 Mins	Cavallo_F	03/16/25 3:18:37	Caller is stating that her daughters father broke into her apartment no longer lives there , unwilling to leave male party name is kevin entry code father states he justs wants to see his daughter, poss. Intoxicated cfs:25 095926
25-021797	45 Linden Street, Hackensack, NJ, 07601	Phone	8	03/18/25 11:39:23			null	Unknown	Linden Street, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	26.98333333	26 Mins 59 Secs	-29.58333333	-1 Hrs 31 Mins	Knapp_J	03/18/25 11:41:26	Discovered on friday, has been contaminating the scene since then ? ? ? ? ? ?
25-022902	171 Kenneth Street, Hackensack, NJ, 07601	Phone	6	03/21/25 14:19:53			null	Unknown	Kenneth Street, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	4.5	4 Mins 30 Secs	-111.3666667	-2 Hrs 09 Mins	Dominguez_P	03/21/25 14:21:37	Rocky auto shop. Report of stolen burgundy chevrolet express van. ? ? ? ? ? ?
25-023424	24 Pulaski Park, Hackensack, NJ, 07601	9-1-1	5	03/23/25 4:55:22			null	Unknown	Pulaski Park, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	2.016666667	2 Mins 01 Secs	-69.86666667	-2 Hrs 51 Mins	Farhi_B	03/23/25 4:57:03	Caller reported that someone broke the lock to his vehicle in an attempt to steal his tools suspect vehicle is white honda crv which fled onto hudson st and possibly rt 80 ? ? ?
25-024100	450 Hackensack Avenue, Hackensack, NJ, 07601	Radio	9	03/25/25 12:04:57			null	Unknown	Hackensack Avenue, 400 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	2.233333333	2 Mins 14 Secs	-54.93333333	-1 Hrs 06 Mins	Klosk_J	03/25/25 12:06:34	Stated female jumped out of car forcibly stole his watch. In front of store drone deployed. Provided overwatch.
25-024791	211 Essex Street, Hackensack, NJ, 07601	Phone	6	03/27/25 12:51:45			null	Unknown	Essex Street, 200 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	9.2	9 Mins 12 Secs	-71	-2 Hrs 49 Mins	Kiselow_G	03/27/25 12:53:26	Caller reported that the 43 possibly occurred overnight / this morning. Waited for building management to arrive before contacting the police ? ? ?
25-025078	2 Park Avenue, Hackensack, NJ, 07601	9-1-1	8	03/28/25 11:13:39			null	Unknown	Park Avenue, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.616666667	3 Mins 37 Secs	-141.3333333	-3 Hrs 39 Mins	Gervasi_J	03/28/25 11:15:09	Caller states his apt was burglarized sometime last night caller found the door to be broken 112442
25-025341	296 Berry Street, Hackensack, NJ, 07601	Phone	8	03/29/25 10:19:00			null	Unknown	Berry Street, 200 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	1.733333333	1 Mins 44 Secs	-77.48333333	-2 Hrs 43 Mins	Competiello_Fa	03/29/25 10:20:04	Caller, navarro gray, reports his father' vehicle may have been stolen overnight. ? ? ? ? ? ?
25-025926	100 Essex Street, Hackensack, NJ, 07601	Phone	7	03/31/25 13:02:43			null	Unknown	Essex Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	4.2	4 Mins 12 Secs	-51.6	-1 Hrs 09 Mins	Ortiz_N	03/31/25 13:04:22	John ross ? ? ? ? ? ?
25-026077	Central Avenue & Second Street, Hackensack, NJ, 07601	9-1-1	7	03/31/25 22:19:40			null	Unknown	Central Avenue & Second Street	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	4.1	4 Mins 05 Secs	-37.25	-1 Hrs 23 Mins	Scott_L	03/31/25 22:21:35	Toyota sienna nj reg j72jjj vehicle was parked @ 1830 hours. Ame back and found belongings had been gone thru
25-026145	45 Essex Street, Hackensack, NJ, 07601	Phone	5	04/01/25 6:22:25			null	Unknown	Essex Street, 0 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	4.833333333	4 Mins 50 Secs	-32.1	-1 Hrs 28 Mins	Ortiz_N	04/01/25 6:24:46	Galss back door found pryed open. Madelyn will meet you out front. Madyln has already entered the building but has been advised to exit. ? ? ?
25-026357	77 Prospect Avenue, Hackensack, NJ, 07601	Phone	7	04/01/25 20:28:40			null	Unknown	Prospect Avenue, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	2.816666667	2 Mins 49 Secs	-75.25	-2 Hrs 45 Mins	Antista_Ma	04/01/25 20:29:54	Caller states his 2024 mazda was broken into ? ? ? ? ? ?
25-027338	75 Fair Street, Hackensack, NJ, 07601	Phone	5	04/04/25 13:05:28			null	Unknown	Fair Street, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	4.55	4 Mins 33 Secs	-120.3	-2 Hrs	Wouters_F	04/04/25 13:08:08	Mother victoria lawson went to hospital son reporting that neighbors check her home when she' not there. They are reporting tv was stolen. Ring doorbell present landlord andre 201 745 7849
25-028849	260 Prospect Avenue, Hackensack, NJ, 07601	9-1-1	8	04/09/25 11:34:58			null	Unknown	Prospect Avenue, 200 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	2.75	2 Mins 45 Secs	-0.183333333	0 Mins	Rivera_W	04/09/25 11:38:04	Someone just broke in and stole items bc 127915 ? ? ?
25-029155	283 Summit Avenue, Hackensack, NJ, 07601	Phone	8	04/10/25 13:49:36			null	Unknown	Summit Avenue, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	5.316666667	5 Mins 19 Secs	-24.63333333	-1 Hrs 36 Mins	Wouters_F	04/10/25 13:52:02	Burglary to auto caught on ring camera ? ? ? ? ? ?
25-029787	1 Park Avenue, Hackensack, NJ, 07601	Radio	8	04/12/25 9:47:06			null	Unknown	Park Avenue, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.316666667	3 Mins 19 Secs	-76.01666667	-2 Hrs 44 Mins	Wouters_F	04/12/25 9:47:28	Shes in the apartment now look for benz gle with pa plates. If located, stop and id driver ? ? ?
25-030391	2 Kinderkamack Road, Hackensack, NJ, 07601	Walk-In	9	04/14/25 11:53:23			null	Unknown	Kinderkamack Road, 0 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	7.45	7 Mins 27 Secs	-167.95	-3 Hrs 13 Mins	Antista_Ma	04/14/25 11:54:51	*******walk in*********** ? ? ? ? ? ?
25-031686	125 River Street, Hackensack, NJ, 07601	Phone	7	04/18/25 23:27:52			null	Unknown	River Street, 100 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	1.916666667	1 Mins 55 Secs	-35.48333333	-1 Hrs 25 Mins	Kiselow_G	04/18/25 23:29:13	River edge is out with male party who reported that he was assaulted at the bus terminal grand and kinderkamack ? ? ?
25-031868	11 Passaic Street, Hackensack, NJ, 07601	9-1-1	8	04/19/25 15:17:07			null	Unknown	Passaic Street, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	3.433333333	3 Mins 26 Secs	-66.96666667	-2 Hrs 54 Mins	Arenas_C	04/19/25 15:18:17	Bc 141524 states someone took his wallet from callers vehicle window was left open. ? ? ?
25-032420	16 Johnson Avenue, Hackensack, NJ, 07601	9-1-1	9	04/21/25 8:04:33			null	Unknown	Johnson Avenue, 0 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	2.616666667	2 Mins 37 Secs	-134.9	-3 Hrs 46 Mins	Sosa_C	04/21/25 8:06:27	Ccad# 25 143362 employee will be in white cadillac waiting for officer. She entered the dental office and there were bottles and lock box strewn around ? ? ?
25-032505	395 South River Street, Hackensack, NJ, 07601	Walk-In	5	04/21/25 12:46:50			null	Unknown	South River Street, 300 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	20.28333333	20 Mins 17 Secs	-48.81666667	-1 Hrs 12 Mins	Wouters_F	04/21/25 12:47:37	***walk in*** occurred / 4/8 4/10 ? ? ? ? ? ?
25-033529	135 First Street, Hackensack, NJ, 07601	Other - See Notes	7	04/24/25 15:16:12			null	Unknown	First Street, 100 Block	Historical	Criminal Sexual Contact - 2C:14-3a	Criminal Sexual Contact	Sexual Offenses	0.733333333	44 Secs	-0.066666667	0 Mins		null	
25-033886	11 East Anderson Street, Hackensack, NJ, 07601	Phone	8	04/25/25 13:44:16			null	Unknown	East Anderson Street, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	3.3	3 Mins 18 Secs	-44.76666667	-1 Hrs 16 Mins	Farhi_B	04/25/25 13:46:57	Suspect rented vehicle 3/19 4/11 and did not return it. ? ? ? ? ? ?
25-034164	46 Newman Street, Hackensack, NJ, 07601	Phone	7	04/26/25 10:30:29			null	Unknown	Newman Street, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	4.933333333	4 Mins 56 Secs	-213.4333333	-4 Hrs 27 Mins		null	
25-034836	530 West Lookout Avenue, Hackensack, NJ, 07601	Phone	9	04/28/25 15:57:33			null	Unknown	West Lookout Avenue, 500 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	9.15	9 Mins 09 Secs	-20.66666667	-1 Hrs 40 Mins	Wouters_F	04/28/25 16:06:35	? ? ? ? ? ?
25-035174	240 Prospect Avenue, Hackensack, NJ, 07601	Phone	8	04/29/25 14:49:23			null	Unknown	Prospect Avenue, 200 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	30.91666667	30 Mins 55 Secs	-33.03333333	-1 Hrs 27 Mins		null	
25-035499	Gamewell Street & South Park Street, Hackensack, NJ, 07601	Walk-In		04/30/25 16:19:23			null	Unknown	Gamewell Street & South Park Street	Historical	Robbery - 2C:15-1	Robbery	Robbery	5.866666667	5 Mins 52 Secs	-60.41666667	-1 Hrs	Cavallo_F	04/30/25 16:24:06	Spanish speaking officer, 17 year old reporting that two parties assaulted him and stole his phone 4/30/2025 4:23 pm he believes one party had knife ? ? ?
25-036368	326 Prospect Avenue, Hackensack, NJ, 07601	Phone	8	05/03/25 11:59:36			null	Unknown	Prospect Avenue, 300 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	8	8 Mins	-116.9166667	-2 Hrs 04 Mins	Cavallo_F	05/03/25 12:04:16	Complainant will be standing by in the lobby, 2023 yamaha no further info at this time, incident occurred within the past 30 days ? ? ?
25-037005	233 Kinderkamack Road, Hackensack, NJ, 07601	9-1-1	9	05/05/25 18:07:55			null	Unknown	Kinderkamack Road, 200 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	32.66666667	32 Mins 39 Secs	-26.28333333	-1 Hrs 34 Mins	Sosa_C	05/05/25 18:09:06	Ccad# 25 163269 indira states her vw was taken in the past hour ? ? ? ? ? ?
25-037180	119 Essex Street, Hackensack, NJ, 07601	9-1-1	6	05/06/25 9:46:13			null	Unknown	Essex Street, 100 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	2.15	2 Mins 09 Secs	-34.8	-1 Hrs 26 Mins	Sosa_C	05/06/25 9:48:22	Ccad# 25 164069 caller stated there is male party attempting to have sex with female without her consent and stated the male has multiple firearms ? ? ?
25-038062	100 John Street, Hackensack, NJ, 07601	Phone	7	05/09/25 0:45:54			null	Unknown	John Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	1.733333333	1 Mins 44 Secs	-323.3333333	-6 Hrs 37 Mins	Cavallo_F	05/09/25 0:46:51	Party sates daughter ex has been stalking her & broker houses window 2 mins in the past 17 ? male bc:25 168098 party is in the backyard. Hispanic male, tall, ski mask with hooded
25-038971	38 Moonachie Road, Hackensack, NJ, 07601	Phone	5	05/12/25 6:50:10			null	Unknown	Moonachie Road, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	3.116666667	3 Mins 07 Secs	-22.96666667	-1 Hrs 38 Mins	Kiselow_G	05/12/25 6:51:35	In parking lot. Left vehicle doors unlocked ? ? ? ? ? ?
25-039095	343 Park Street, Hackensack, NJ, 07601	Walk-In	8	05/12/25 13:20:26			null	Unknown	Park Street, 300 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	11.86666667	11 Mins 52 Secs	-53.78333333	-1 Hrs 07 Mins	Kiselow_G	05/12/25 13:25:52	Occurred on the first of the month. Fraud on debit card. Packet complete walk in ? ? ?
25-039279	4 Valley Health Plaza, Hackensack, NJ, 07601	Phone		05/13/25 1:48:55			null	Unknown	Valley Health Plaza, 0 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	0.266666667	16 Secs	-61.95	-2 Hrs 59 Mins		null	
25-039451	135 First Street, Hackensack, NJ, 07601	Other - See Notes	7	05/13/25 15:15:09			null	Unknown	First Street, 100 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	0.866666667	52 Secs	-0.6	0 Mins		null	
25-039778	520 River Street, Hackensack, NJ, 07601	Phone	9	05/14/25 15:30:51			null	Unknown	River Street, 500 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	1.583333333	1 Mins 35 Secs	-68	-2 Hrs 52 Mins	Kiselow_G	05/14/25 15:31:13	26 from lot ? ? ? ? ? ?
25-039963	90 Railroad Avenue, Hackensack, NJ, 07601	Walk-In	7	05/15/25 8:15:38			null	Unknown	Railroad Avenue, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	0.65	39 Secs	-36.16666667	-1 Hrs 24 Mins		null	
25-040394	33 Henry Place, Hackensack, NJ, 07601	Walk-In	5	05/16/25 13:20:08			null	Unknown	Henry Place, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	12.03333333	12 Mins 02 Secs	-87.6	-2 Hrs 33 Mins	Ortiz_N	05/16/25 13:23:22	Walk in reporting her apartment was burglarized twice this week. Monday and today. Party is already reluctant to provide address. ? ? ?
25-041339	55 Clinton Place, Hackensack, NJ, 07601	9-1-1	9	05/19/25 19:32:34			null	Unknown	Clinton Place, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	2.083333333	2 Mins 05 Secs	-72.83333333	-2 Hrs 48 Mins	Sroka_T	05/19/25 19:34:01	Caller rpeorting her grey ford escape was stolen last saw the vehicle at 8pm yesterday in the parking lot keys not in the vehicle ccad # 25 182882
25-041571	461 Passaic Street, Hackensack, NJ, 07601	Walk-In	8	05/20/25 13:30:15			null	Unknown	Passaic Street, 400 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	34.36666667	34 Mins 22 Secs	-29.05	-1 Hrs 31 Mins	Kiselow_G	05/20/25 13:34:08	Unknown suspect entered vehicle and stole handicapped parking placard ? ? ? ? ? ?
25-041892	43 Maple Avenue, Hackensack, NJ, 07601	Walk-In	9	05/21/25 14:05:42			null	Unknown	Maple Avenue, 0 Block	Historical	Criminal Sexual Contact - 2C:14-3a	Criminal Sexual Contact	Sexual Offenses	44.75	44 Mins 45 Secs	-78.96666667	-2 Hrs 42 Mins	Kiselow_G	05/21/25 14:42:06	Incident occurred on the 13th walk in ? ? ?
25-042272	18 East Camden Street, Hackensack, NJ, 07601	Phone	8	05/22/25 21:35:24			null	Unknown	East Camden Street, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.033333333	3 Mins 02 Secs	-38.18333333	-1 Hrs 22 Mins	Wouters_F	05/22/25 21:37:39	Ex bf entered apartment and stole $30,000 from the safe. Actor on scene ? ? ? ? ? ?
25-042950	20 Prospect Avenue, Hackensack, NJ, 07601	Phone	7	05/25/25 8:51:39			null	Unknown	Prospect Avenue, 0 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	44	44 Mins	-61.66666667	-2 Hrs 59 Mins	Ortiz_N	05/25/25 8:52:48	Burglary occurred earlier today, humc never notified hpd ? ? ? ? ? ?
25-043899	160 River Street, Hackensack, NJ, 07601	Walk-In		05/28/25 16:53:40			null	Unknown	River Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.533333333	3 Mins 32 Secs	-61.26666667	-2 Hrs 59 Mins	Han_J	05/28/25 16:55:40	Burglary that occurred in the past. Pai of pants and ss card. ? ? ? ? ? ?
25-044042	Park Street & Passaic Street, Hackensack, NJ, 07601	9-1-1	8	05/29/25 3:57:10			null	Unknown	Park Street & Passaic Street	Historical	Robbery - 2C:15-1	Robbery	Robbery	2.983333333	2 Mins 59 Secs	-67.23333333	-2 Hrs 53 Mins	Lemanowicz_S	05/29/25 3:59:10	Caller stating that male party punched the caller in the face 25 194998 suspect: hispanic male party wearing red hoodie, black pants caller is wearing grey hoodie and blue pants in the parking lot
25-045625	1 University Plaza Drive, Hackensack, NJ, 07601	Phone	9	06/03/25 6:10:31			null	Unknown	University Plaza Drive, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	0.883333333	53 Secs	-111.9166667	-2 Hrs 09 Mins	Farhi_B	06/03/25 6:12:29	Caller reports his red crv was broken into. Will be standing by. ? ? ? ? ? ?
25-045839	160 Overlook Avenue, Hackensack, NJ, 07601	Phone	7	06/03/25 19:30:42			null	Unknown	Overlook Avenue, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	16.98333333	16 Mins 59 Secs	-64.8	-2 Hrs 56 Mins	Ortiz_N	06/03/25 19:31:47	Stolen yamaha r1 meet near rear entrance to garage ? ? ? ? ? ?
25-045993	167 Central Avenue, Hackensack, NJ, 07601	Other - See Notes	7	06/04/25 8:58:28			null	Unknown	Central Avenue, 100 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	0	0 Secs	0	0 Mins	Tanucilli_J	06/04/25 9:00:33	Bcpo svu follow incident allegedly occurred on 5/31/2025 never report to hpd only bcpo svu ? ? ? ? ? ?
25-046075	6-8 Prospect Avenue, Hackensack, NJ, 07601	Phone		06/04/25 14:05:59			null	Unknown	Prospect Avenue, 0 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	86.55	86 Mins 33 Secs	-133.1333333	-3 Hrs 47 Mins	Cavallo_F	06/04/25 14:08:54	Complainant reporting that she was sexually assaulted in vehicle on june 1st ? ? ? ? ? ?
25-046290	39 Union Street, Hackensack, NJ, 07601	9-1-1	7	06/05/25 6:47:22			null	Unknown	Union Street, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	13.53333333	13 Mins 32 Secs	-28.1	-1 Hrs 32 Mins	Lemanowicz_S	06/05/25 6:53:06	3rd party reporting burg to veh blk male in his 20s wearing blk shirt with face mask light skinned male with hoodie 25 205362 suspect fled in white infiniti with partial plate pg
25-046294	410 Simons Avenue, Hackensack, NJ, 07601	9-1-1	6	06/05/25 6:53:06			null	Unknown	Simons Avenue, 400 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	0	0 Secs	0	0 Mins	Lemanowicz_S	06/05/25 6:59:20	2 male parties hoodies entered into mv and took off wht nissan east on summit 2 blk male dressed in all black / victim vehicle reg p55unm 25 205365
25-047026	414 Hackensack Avenue, Hackensack, NJ, 07601	Phone	9	06/07/25 17:14:43			null	Unknown	Hackensack Avenue, 400 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	3.5	3 Mins 30 Secs	-60.95	-1 Hrs	Kiselow_G	06/07/25 17:16:36	Complainant will be standing by her vehicle in front of the 1000 building. Unknown suspect smashed out the windows of her vehicle ? ? ?
25-047203	282 American Legion Drive, Hackensack, NJ, 07601	9-1-1	7	06/08/25 10:11:05			null	Unknown	American Legion Drive, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	5.433333333	5 Mins 26 Secs	-14.26666667	-1 Hrs 46 Mins	Lemanowicz_S	06/08/25 10:11:56	Burglary to auto smashed window and took bag. Ford escape t64klc nj reg on the street. Vehicle last seen 0130 . Intact. 25 210025 ? ? ?
25-048048	150 Main Street, Hackensack, NJ, 07601	Phone		06/11/25 4:34:09			null	Unknown	Main Street, 100 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	7.433333333	7 Mins 26 Secs	-114.8333333	-2 Hrs 06 Mins	Ortiz_N	06/11/25 4:41:04	Toyota 4 runner grey just stolen amazon driver ? ? ? ? ? ?
25-048869	211 Essex Street, Hackensack, NJ, 07601	Phone	6	06/13/25 14:52:59			null	Unknown	Essex Street, 200 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	6.3	6 Mins 18 Secs	-33.38333333	-1 Hrs 27 Mins		null	
25-050281	259 Park Street, Hackensack, NJ, 07601	Phone	8	06/18/25 11:09:24			null	Unknown	Park Street, 200 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	23.16666667	23 Mins 10 Secs	-55.48333333	-1 Hrs 05 Mins	Knapp_J	06/18/25 11:10:12	Someone entered and stole the family cat ? ? ? ? ? ?
25-050476	125 Lawrence Street, Hackensack, NJ, 07601	Phone	7	06/18/25 23:42:18			null	Unknown	Lawrence Street, 100 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	4.5	4 Mins 30 Secs	-73.43333333	-2 Hrs 47 Mins	Competiello_Fa	06/18/25 23:44:14	Caller states her 7 / was sexually assaulted by the father. Will meet officer outside. Tot lyndhurst pd ? ? ?
25-051165	81 Euclid Avenue, Hackensack, NJ, 07601	Walk-In	9	06/21/25 10:42:26			null	Unknown	Euclid Avenue, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	11.43333333	11 Mins 26 Secs	-21.36666667	-1 Hrs 39 Mins	Wouters_F	06/21/25 10:43:22	***walk in*** ? ? ? ? ? ?
25-051170	336 Main Street, Hackensack, NJ, 07601	9-1-1	8	06/21/25 11:03:13			null	Unknown	Main Street, 300 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	0	0 Secs	0	0 Mins	Antista_Ma	06/21/25 11:04:19	Grey toyota highlander just happened.... No direction of flight 25 228333 ? ? ?
25-051478	95 Tracy Place, Hackensack, NJ, 07601	Phone	7	06/22/25 11:25:43			null	Unknown	Tracy Place, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	6.416666667	6 Mins 25 Secs	-51.45	-1 Hrs 09 Mins		null	
25-053161	77 Prospect Avenue, Hackensack, NJ, 07601	9-1-1	7	06/27/25 14:18:09			null	Unknown	Prospect Avenue, 0 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	50.28333333	50 Mins 17 Secs	-41.33333333	-1 Hrs 19 Mins	Gervasi_J	06/27/25 14:19:03	Caller states his apartment was robbed. Wife was home but did not hear 237451 ? ? ?
25-053984	33 East Broadway, Hackensack, NJ, 07601	9-1-1	5	06/30/25 7:33:04			null	Unknown	East Broadway, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	3.1	3 Mins 06 Secs	-26.11666667	-1 Hrs 34 Mins	Wouters_F	06/30/25 7:33:56	Tool stolen from vehicle. 25 240989 ? ? ?
25-054058	100 Essex Street, Hackensack, NJ, 07601	Phone	7	06/30/25 11:16:33			null	Unknown	Essex Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	2.6	2 Mins 36 Secs	-23.3	-1 Hrs 37 Mins	Wouters_F	06/30/25 11:17:34	Currently vacant room, see comp on site. ? ? ? ? ? ?
25-054890	175 Passaic Street, Hackensack, NJ, 07601	Phone	8	07/02/25 19:40:35			null	Unknown	Passaic Street, 100 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	1.416666667	1 Mins 25 Secs	-28.01666667	-1 Hrs 32 Mins	Kiselow_G	07/02/25 19:41:35	Caller reported that jewelry is missing from her residence ? ? ? ? ? ?
25-055122	400  Hackensack Avenue, Hackensack, NJ, 07601	Phone	9	07/03/25 10:21:39			null	Unknown	Hackensack Avenue, 400 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	27.63333333	27 Mins 38 Secs	-21.33333333	-1 Hrs 39 Mins	Dominguez_P	07/03/25 10:23:16	Meet connie in reference to burglary of storage closet. She will meet officer out front of cheesecake factory ? ? ?
25-055295	275 Beech Street, Hackensack, NJ, 07601	Other - See Notes	7	07/03/25 21:34:51			null	Unknown	Beech Street, 200 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	0	0 Secs	0	0 Mins	Laranunez_C	07/03/25 22:11:28	Notified by svu det. Huda ? ? ? ? ? ?
25-056435	65 Court Street, Hackensack, NJ, 07601	9-1-1	5	07/07/25 14:40:14			null	Unknown	Court Street, 0 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	3.766666667	3 Mins 46 Secs	-245.5	-5 Hrs 55 Mins	Lyak_R	07/07/25 14:41:56	Caller stating someone pepper sprayed him and took his phone behind pepboys ? ? ?
25-056999	240 First Street, Hackensack, NJ, 07601	Walk-In	8	07/09/25 0:29:06			null	Unknown	First Street, 200 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	3.016666667	3 Mins 01 Secs	-37.48333333	-1 Hrs 23 Mins	Wouters_F	07/09/25 0:29:34	**walk in** ? ? ? ? ? ?
25-057343	50 Main Street, Hackensack, NJ, 07601	9-1-1	7	07/10/25 2:32:02			null	Unknown	Main Street, 0 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	1.45	1 Mins 27 Secs	-141.5333333	-3 Hrs 39 Mins	Wouters_F	07/10/25 2:33:18	Uber driver stating male passenger was assaulted. Silver honda civic 25 255340 ? ? ?
25-058041	4 Camden Street, Hackensack, NJ, 07601	Phone	8	07/12/25 7:00:06			null	Unknown	Camden Street, 0 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	3.733333333	3 Mins 44 Secs	-77.35	-2 Hrs 43 Mins	Ortiz_N	07/12/25 7:01:11	Caller reporting the windows to store is broken does not see anyone inside bcc 25 258342 ? ? ?
25-058331	215 Charles Street, Hackensack, NJ, 07601	Phone	6	07/13/25 2:47:47			null	Unknown	Charles Street, 200 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	2.783333333	2 Mins 47 Secs	-77.9	-2 Hrs 43 Mins	Cavallo_F	07/13/25 2:49:52	Caller reports that her boyfriend assulted her in car and she was able get out of the car. Female is wearing grey pants and white shirt and white sneakers boyfriend may still be in the area in vehicle.
25-058451	210 Main Street, Hackensack, NJ, 07601	9-1-1	8	07/13/25 13:18:19			null	Unknown	Main Street, 200 Block	Historical	Burglary - Residence - 2C:18-2	Burglary - Residence	Burglary - Residence	25.05	25 Mins 03 Secs	-66.91666667	-2 Hrs 54 Mins	Sosa_C	07/13/25 13:19:16	Ccad# 25 259896 storage unit was broken into ? ? ? ? ? ?
25-058726	80 South River Street, Hackensack, NJ, 07601	Walk-In	5	07/14/25 13:09:00			null	Unknown	South River Street, 0 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	10.51666667	10 Mins 31 Secs	-35.78333333	-1 Hrs 25 Mins	Knapp_J	07/14/25 13:16:23	Walk in reporting he was robbed at costco last thursday ? ? ? ? ? ?
25-059260	18 Lodi Street, Hackensack, NJ, 07601	Phone	5	07/16/25 4:59:48			null	Unknown	Lodi Street, 0 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	1.183333333	1 Mins 11 Secs	-16	-1 Hrs 44 Mins	Wouters_F	07/16/25 5:01:31	Missing money from his white car parked near address ? ? ? ? ? ?
25-060006	30 Prospect Avenue, Hackensack, NJ, 07601	9-1-1	7	07/18/25 5:46:58			null	Unknown	Prospect Avenue, 0 Block	Historical	Sexual Assault - 2C:14-2b	Sexual Assault	Sexual Offenses	2.816666667	2 Mins 49 Secs	-479.0166667	-8 Hrs 01 Mins	Kiselow_G	07/18/25 5:49:01	48 yof stating she was raped sexually assaulted bleeding form the anal area as per the caller the male party is at the house . Located in the lobby bergen county cad # 25 267094
25-060143	65 Court Street, Hackensack, NJ, 07601	Walk-In	5	07/18/25 15:51:45			null	Unknown	Court Street, 0 Block	Historical	Robbery - 2C:15-1	Robbery	Robbery	2.9	2 Mins 54 Secs	-51.95	-1 Hrs 09 Mins		null	
25-060392	307 Maple Hill Drive, Hackensack, NJ, 07601	9-1-1	8	07/19/25 14:30:03			null	Unknown	Maple Hill Drive, 300 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	2.066666667	2 Mins 04 Secs	-46.88333333	-1 Hrs 14 Mins	Sosa_C	07/19/25 14:31:03	Ccad# 25 269088 3 vehicles broken into ? ? ? ? ? ?
25-060401	307 Maple Hill Drive, Hackensack, NJ, 07601	Radio	8	07/19/25 14:59:35			null	Unknown	Maple Hill Drive, 300 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	0	0 Secs	0	0 Mins		null	
25-060402	307 Maple Hill Drive, Hackensack, NJ, 07601	Radio		07/19/25 15:01:51			null	Unknown	Maple Hill Drive, 300 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	0	0 Secs	0	0 Mins		null	
25-061119	33 Oak Street, Hackensack, NJ, 07601	9-1-1	9	07/21/25 18:35:31			null	Unknown	Oak Street, 0 Block	Historical	Motor Vehicle Theft - 2C:20-3	Motor Vehicle Theft	Motor Vehicle Theft	13.75	13 Mins 45 Secs	-234.0666667	-4 Hrs 06 Mins	Scott_L	07/21/25 18:37:42	Caller stated his veh was stolen from his garage last seen this morning just got home 5 min ago garage was broken into and veh stolen green lamboughini ccad# 25 272177
25-061760	469 Passaic Street, Hackensack, NJ, 07601	Walk-In	8	07/23/25 12:07:08			null	Unknown	Passaic Street, 400 Block	Historical	Burglary - Auto - 2C:18-2	Burglary - Auto	Burglary - Auto	47.6	47 Mins 36 Secs	-0.35	0 Mins	Kiselow_G	07/23/25 12:09:57	Walk in ? ? ? ? ? ?
25-062452	90 Hackensack Avenue, Hackensack, NJ, 07601	Phone	9	07/25/25 11:03:20			null	Unknown	Hackensack Avenue, 0 Block	Historical	Burglary - Commercial - 2C:18-2	Burglary - Commercial	Burglary - Commercial	3.266666667	3 Mins 16 Secs	-38.21666667	-1 Hrs 22 Mins	Kiselow_G	07/25/25 11:05:36	Unknown suspects entered the rear of the business. Detectives were notified ? ? ? ? ? ?