// 🕒 2025-07-23-16-00-00
// Project: SCRPA_Time_v2/Final_Working_PowerBI_Solution
// Author: R. A. Carucci
// Purpose: Complete working M Code based on actual data structure analysis

// =============================================================================
// ALL_CRIMES Query - Final Working Version
// =============================================================================

let
    Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\05_EXPORTS\_RMS\SCRPA"),
    FilteredExcel = Table.SelectRows(Source, each [Extension] = ".xlsx" and Record.FieldOrDefault([Attributes], "Hidden", false) <> true),
    Sorted = Table.Sort(FilteredExcel,{{"Date modified", Order.Descending}}),
    LatestFile = Table.FirstN(Sorted, 1),

    Transform_File = (Parameter2 as binary) =>
        let
            // ✅ Handle multiple sheets safely
            Source = Excel.Workbook(Parameter2, null, true),
            FilteredSheets = Table.SelectRows(Source, each [Kind] = "Sheet"),
            Sheet1_Sheet = if Table.RowCount(FilteredSheets) > 0 then FilteredSheets{0}[Data] else error "No valid sheets found",

            #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),

            // ✅ Type conversions with error handling for actual column structure
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
                {"Case Number", type text},
                {"Incident Date", type date},
                {"Incident Time", type time},
                {"Incident Date_Between", type date},
                {"Incident Time_Between", type time},
                {"Report Date", type date},
                {"Report Time", type time},
                {"Incident Type_1", type text},
                {"Incident Type_2", type text},
                {"Incident Type_3", type text},
                {"FullAddress", type text},
                {"Officer of Record", type text}
            }),

            // ✅ Add calculated date/time columns with cascading logic
            WithIncidentDate = Table.AddColumn(#"Changed Type", "Incident_Date", each
                if [Incident Date] <> null then [Incident Date]
                else if [Incident Date_Between] <> null then [Incident Date_Between]
                else if [Report Date] <> null then [Report Date]
                else null, type date),

            WithIncidentTime = Table.AddColumn(WithIncidentDate, "Incident_Time", each
                if [Incident Time] <> null then [Incident Time]
                else if [Incident Time_Between] <> null then [Incident Time_Between]
                else if [Report Time] <> null then Time.From([Report Time])
                else null, type time),

            // ✅ Add StartOfHour calculation
            WithStartOfHour = Table.AddColumn(WithIncidentTime, "StartOfHour", each
                if [Incident_Time] <> null then Time.StartOfHour([Incident_Time]) else null, type time),

            // ✅ CORRECTED TimeOfDay buckets - exact project specifications
            WithTimeOfDay = Table.AddColumn(WithStartOfHour, "TimeOfDay", each
                let t = [Incident_Time] in
                if t = null then "Unknown"
                else if t >= #time(0,0,0) and t < #time(4,0,0) then "00:00–03:59 Early Morning"
                else if t >= #time(4,0,0) and t < #time(8,0,0) then "04:00–07:59 Morning"
                else if t >= #time(8,0,0) and t < #time(12,0,0) then "08:00–11:59 Morning Peak"
                else if t >= #time(12,0,0) and t < #time(16,0,0) then "12:00–15:59 Afternoon"
                else if t >= #time(16,0,0) and t < #time(20,0,0) then "16:00–19:59 Evening Peak"
                else "20:00–23:59 Night", type text),

            // ✅ Add Block calculation using FullAddress (not FullAddress2)
            WithBlock = Table.AddColumn(WithTimeOfDay, "Block", each
                let
                    addr = [FullAddress] ?? "",
                    streetNum = try Number.FromText(Text.BeforeDelimiter(addr, " ")) otherwise null,
                    streetName = Text.Trim(Text.BeforeDelimiter(Text.AfterDelimiter(addr, " "), ","))
                in
                    if streetNum <> null and streetName <> "" then
                        streetName & ", " & Text.From(Number.IntegerDivide(streetNum, 100) * 100) & " Block"
                    else if streetName <> "" then
                        streetName & ", Unknown Block"
                    else "Unknown Block", type text),

            // ✅ Create ALL_INCIDENTS before unpivoting (for filtering logic)
            WithAllIncidents = Table.AddColumn(WithBlock, "ALL_INCIDENTS", each
                Text.Combine(
                    List.RemoveNulls({
                        [Incident Type_1],
                        [Incident Type_2],
                        [Incident Type_3]
                    }), " - "
                ), type text),

            // ✅ Add Period calculation
            WithPeriod = Table.AddColumn(WithAllIncidents, "Period", each
                let
                    incidentDate = [Incident_Date],
                    today = Date.From(DateTime.LocalNow()),
                    daysDiff = if incidentDate <> null then Duration.Days(today - incidentDate) else 999
                in
                    if daysDiff <= 7 then "7-Day"
                    else if daysDiff <= 28 then "28-Day"
                    else if incidentDate <> null and Date.Year(incidentDate) = Date.Year(today) then "YTD"
                    else "Historical", type text),

            // ✅ Filter out excluded case and Historical records BEFORE unpivoting
            FilteredRows = Table.SelectRows(WithPeriod, each
                [Case Number] <> "25-057654" and [Period] <> "Historical"
            ),

            // ✅ UNPIVOT the incident type columns
            IncidentColumns = {"Incident Type_1", "Incident Type_2", "Incident Type_3"},
            KeepColumns = Table.ColumnNames(FilteredRows),
            IdColumns = List.Difference(KeepColumns, IncidentColumns),

            Unpivoted = Table.UnpivotOtherColumns(FilteredRows, IdColumns, "IncidentColumn", "IncidentType"),

            // ✅ Remove null/empty incident types (handles 56% missing Type_2, 80% missing Type_3)
            CleanedIncidents = Table.SelectRows(Unpivoted, each
                [IncidentType] <> null and [IncidentType] <> ""
            ),

            // ✅ Crime categorization using both individual and combined incident types
            WithCrimeCategory = Table.AddColumn(CleanedIncidents, "Crime_Category", each
                let
                    incident = Text.Upper([IncidentType] ?? ""),
                    allIncidents = Text.Upper([ALL_INCIDENTS] ?? "")
                in
                    if Text.Contains(incident, "MOTOR VEHICLE THEFT") or Text.Contains(allIncidents, "MOTOR VEHICLE THEFT") then "Motor Vehicle Theft"
                    else if Text.Contains(incident, "ROBBERY") or Text.Contains(allIncidents, "ROBBERY") then "Robbery"
                    else if (Text.Contains(incident, "BURGLARY") and Text.Contains(incident, "AUTO")) or (Text.Contains(allIncidents, "BURGLARY") and Text.Contains(allIncidents, "AUTO")) then "Burglary – Auto"
                    else if Text.Contains(incident, "SEXUAL") or Text.Contains(allIncidents, "SEXUAL") then "Sexual Offenses"
                    else if (Text.Contains(incident, "BURGLARY") and Text.Contains(incident, "COMMERCIAL")) or (Text.Contains(allIncidents, "BURGLARY") and Text.Contains(allIncidents, "COMMERCIAL")) then "Burglary – Commercial"
                    else if (Text.Contains(incident, "BURGLARY") and Text.Contains(incident, "RESIDENCE")) or (Text.Contains(allIncidents, "BURGLARY") and Text.Contains(allIncidents, "RESIDENCE")) then "Burglary – Residence"
                    else "Other", type text),

            // ✅ Remove duplicates by Case Number (keeps first occurrence after unpivot)
            DistinctCases = Table.Distinct(WithCrimeCategory, {"Case Number"})
        in
            DistinctCases,

    InvokedCustom = Table.AddColumn(LatestFile, "Transform_File", each Transform_File([Content])),
    #"Expanded Transform_File" = Table.ExpandTableColumn(InvokedCustom, "Transform_File", Table.ColumnNames(Transform_File(LatestFile{0}[Content]))),
    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Transform_File", Table.ColumnNames(Transform_File(LatestFile{0}[Content])))
in
    #"Removed Other Columns"

    let
        Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\05_EXPORTS\_CAD\SCRPA"),
        FilteredExcel = Table.SelectRows(Source, each [Extension] = ".xlsx" and Record.FieldOrDefault([Attributes], "Hidden", false) <> true),
        Sorted = Table.Sort(FilteredExcel,{{"Date modified", Order.Descending}}),
        LatestFile = Table.FirstN(Sorted, 1),

        Transform_File = (Parameter2 as binary) =>
            let
                // ✅ Handle multiple sheets safely
                Source = Excel.Workbook(Parameter2, null, true),
                FilteredSheets = Table.SelectRows(Source, each [Kind] = "Sheet"),
                Sheet1_Sheet = if Table.RowCount(FilteredSheets) > 0 then FilteredSheets{0}[Data] else error "No valid CAD sheets found",

                #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),

                // ✅ FIXED: Handle Time Spent and Time Response as time strings (00:21:20 format)
                #"Fixed Time Columns" = Table.TransformColumns(#"Promoted Headers", {
                    {"Time Spent", each
                        let
                            value = _
                        in
                            if value = null then null
                            else if value is time then Duration.TotalMinutes(value)
                            else if value is text then
                                try
                                    let
                                        timeValue = Time.FromText(value),
                                        minutes = Duration.TotalMinutes(timeValue)
                                    in if minutes < 0 then null else minutes
                                otherwise null
                            else if value is number then if value < 0 then null else value
                            else null
                        , type number
                    },
                    {"Time Response", each
                        let
                            value = _
                        in
                            if value = null then null
                            else if value is time then Duration.TotalMinutes(value)
                            else if value is text then
                                try
                                    let
                                        timeValue = Time.FromText(value),
                                        minutes = Duration.TotalMinutes(timeValue)
                                    in if minutes < 0 then null else minutes
                                otherwise null
                            else if value is number then if value < 0 then null else value
                            else null
                        , type number
                    }
                }),

                // ✅ Add Block calculation using FullAddress2 (CAD uses FullAddress2, not FullAddress)
                WithBlock = Table.AddColumn(#"Fixed Time Columns", "Block", each
                    let
                        addr = [FullAddress2] ?? "",
                        streetNum = try Number.FromText(Text.BeforeDelimiter(addr, " ")) otherwise null,
                        streetName = Text.Trim(Text.BeforeDelimiter(Text.AfterDelimiter(addr, " "), ","))
                    in
                        if streetNum <> null and streetName <> "" then
                            streetName & ", " & Text.From(Number.IntegerDivide(streetNum, 100) * 100) & " Block"
                        else if streetName <> "" then
                            streetName & ", Unknown Block"
                        else "Unknown Block", type text)
            in
                WithBlock,

        InvokedCustom = Table.AddColumn(LatestFile, "Transform_File", each Transform_File([Content])),
        #"Expanded Transform_File" = Table.ExpandTableColumn(InvokedCustom, "Transform_File", Table.ColumnNames(Transform_File(LatestFile{0}[Content]))),
        #"Removed Other Columns" = Table.SelectColumns(#"Expanded Transform_File", Table.ColumnNames(Transform_File(LatestFile{0}[Content])))
    in
        #"Removed Other Columns"

        // 🕒 2025-07-22-13-45-00
// Project: SCRPA_Analysis/Updated_RMS_Data_Query
// Author: R. A. Carucci
// Purpose: Complete RMS_Data M-Code with fixed null handling and data type conversions

let
    // RMS Data Source
    Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\05_EXPORTS\_RMS\SCRPA"),
    FilteredFiles = Table.SelectRows(Source, each [Extension] = ".xlsx" and Record.FieldOrDefault([Attributes],"Hidden",false) <> true),
    SortedFiles = Table.Sort(FilteredFiles, {{"Date modified", Order.Descending}}),
    LatestFile = Table.FirstN(SortedFiles, 1),

    TransformRMS = (FileBinary as binary) =>
        let
            Workbook = Excel.Workbook(FileBinary, null, true),
            FirstSheet = try Workbook{[Item="Sheet1",Kind="Sheet"]}[Data]
                        otherwise try Workbook{0}[Data]
                        otherwise Workbook{[Kind="Sheet"]}[Data],
            Headers = Table.PromoteHeaders(FirstSheet, [PromoteAllScalars=true]),

            // Get available columns to avoid errors
            AvailableColumns = Table.ColumnNames(Headers),

            // Safe data type conversion with null handling - only for columns that exist
            SafeTyped = Table.TransformColumnTypes(Headers,
                List.Select({
                    {"Case Number", type text},
                    {"CaseNumber", type text},
                    {"IncidentType1", type text},
                    {"IncidentType2", type text},
                    {"IncidentType3", type text},
                    {"IncidentType", type text},
                    {"FullAddress", type text},
                    {"Zone", Int64.Type},
                    {"Officer", type text},
                    {"OfficerOfRecord", type text},
                    {"Disposition", type text}
                }, each List.Contains(AvailableColumns, _{0}))),

            // Crime category logic with safe text handling
            WithCrimeCategory = Table.AddColumn(SafeTyped, "Crime_Category", each
                let
                    incidentText = try
                        if List.Contains(AvailableColumns, "IncidentType1") and [IncidentType1] <> null then Text.Upper([IncidentType1])
                        else if List.Contains(AvailableColumns, "IncidentType") and [IncidentType] <> null then Text.Upper([IncidentType])
                        else ""
                    otherwise ""
                in
                    if Text.Contains(incidentText,"MOTOR VEHICLE THEFT") then "Motor Vehicle Theft"
                    else if List.AnyTrue({
                        Text.Contains(incidentText,"BURGLARY - AUTO"),
                        Text.Contains(incidentText,"THEFT FROM MOTOR VEHICLE")
                    }) then "Burglary Auto"
                    else if List.AnyTrue({
                        Text.Contains(incidentText,"BURGLARY - COMMERCIAL"),
                        Text.Contains(incidentText,"BURGLARY - RESIDENCE")
                    }) then "Burglary - Comm & Res"
                    else if Text.Contains(incidentText,"ROBBERY") then "Robbery"
                    else if List.AnyTrue({
                        Text.Contains(incidentText,"SEXUAL"),
                        Text.Contains(incidentText,"RAPE")
                    }) then "Sexual Offenses"
                    else "Other", type text),

            // Safe incident date conversion - check multiple possible date columns
            WithIncidentDate = Table.AddColumn(WithCrimeCategory, "Incident_Date", each
                try
                    if List.Contains(AvailableColumns, "IncidentDate") and [IncidentDate] <> null then
                        Date.From([IncidentDate])
                    else if List.Contains(AvailableColumns, "IncidentDateBetween") and [IncidentDateBetween] <> null then
                        Date.From([IncidentDateBetween])
                    else if List.Contains(AvailableColumns, "ReportDate") and [ReportDate] <> null then
                        Date.From([ReportDate])
                    else if List.Contains(AvailableColumns, "Incident Date") and [Incident Date] <> null then
                        Date.From([Incident Date])
                    else null
                otherwise null, type date),

            // Safe period calculation
            WithPeriod = Table.AddColumn(WithIncidentDate, "Period", each
                try
                    let
                        incDate = [Incident_Date],
                        today = Date.From(DateTime.LocalNow()),
                        daysDiff = if incDate <> null then Duration.Days(today - incDate) else 999
                    in
                        if daysDiff <= 7 then "7-Day"
                        else if daysDiff <= 28 then "28-Day"
                        else if incDate <> null and Date.Year(incDate) = Date.Year(today) then "YTD"
                        else "Historical"
                otherwise "Historical", type text),

            // Add ALL_INCIDENTS field safely
            WithAllIncidents = Table.AddColumn(WithPeriod, "ALL_INCIDENTS", each
                try
                    if List.Contains(AvailableColumns, "IncidentType1") and [IncidentType1] <> null then [IncidentType1]
                    else if List.Contains(AvailableColumns, "IncidentType") and [IncidentType] <> null then [IncidentType]
                    else "Unknown"
                otherwise "Unknown", type text),

            // Add Block calculation if address exists
            WithBlock = if List.Contains(AvailableColumns, "FullAddress") then
                Table.AddColumn(WithAllIncidents, "Block", each
                    try
                        let
                            addr = if [FullAddress] <> null then [FullAddress] else "",
                            streetNum = try Number.FromText(Text.BeforeDelimiter(addr, " ")) otherwise null,
                            streetName = Text.Trim(Text.BeforeDelimiter(Text.AfterDelimiter(addr, " "), ","))
                        in
                            if streetNum <> null and streetName <> "" then
                                streetName & ", " & Text.From(Number.IntegerDivide(streetNum, 100) * 100) & " Block"
                            else if streetName <> "" then
                                streetName & ", Unknown Block"
                            else "Unknown Block"
                    otherwise "Unknown Block", type text)
            else
                Table.AddColumn(WithAllIncidents, "Block", each "Unknown Block", type text),

            // Standardize column names - handle both naming conventions
            StandardizedColumns = Table.RenameColumns(WithBlock,
                List.Select({
                    {"CaseNumber", "Case Number"},
                    {"OfficerOfRecord", "Officer"},
                    {"Incident Date", "Incident_Date_Original"}
                }, each List.Contains(Table.ColumnNames(WithBlock), _{0})), MissingField.Ignore)
        in
            StandardizedColumns,

    InvokedRMS = Table.AddColumn(LatestFile, "RMS_Data", each TransformRMS([Content]), type table),
    ExpandedRMS = Table.ExpandTableColumn(InvokedRMS, "RMS_Data",
        Table.ColumnNames(TransformRMS(LatestFile{0}[Content]))),
    FinalRMS = Table.SelectColumns(ExpandedRMS,
        Table.ColumnNames(TransformRMS(LatestFile{0}[Content]))),
    #"Trimmed Text" = Table.TransformColumns(FinalRMS,{{"Narrative", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Narrative", Text.Clean, type text}})
in
    #"Cleaned Text"

    // Query: TimeOfDaySort
let
    TimeOfDaySort = #table(
        type table [TimeOfDay = text, SortOrder = Int64.Type],
        {
            {"00:00–03:59 - Early Morning", 1},
            {"04:00–07:59 - Morning", 2},
            {"08:00–11:59 - Morning Peak", 3},
            {"12:00–15:59 - Afternoon", 4},
            {"16:00–19:59 - Evening Peak", 5},
            {"20:00–23:59 - Night", 6},
            {"Unknown", 99}
        }
    )
in
    TimeOfDaySort

    // Use your existing cycle query
let
    Source = Excel.Workbook(File.Contents("C:\Users\carucci_r\OneDrive - City of Hackensack\09_Reference\Temporal\SCRPA_Cycle\7Day_28Day_Cycle_20250414.xlsx"), null, true),
    CycleData = Source{[Item="7Day_28Day_250414",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(CycleData),
    Typed = Table.TransformColumnTypes(Headers,{
        {"Report_Due_Date", type date},
        {"7_Day_Start", type date},
        {"7_Day_End", type date},
        {"28_Day_Start", type date},
        {"28_Day_End", type date}
    })
in
    Typed

    // 🕒 2025-07-22-14-30-00
// Project: SCRPA_Analysis/Corrected_RMS_Data_Final
// Author: R. A. Carucci
// Purpose: RMS_Data query using actual column names from your data structure

let
    RMS = ALL_CRIMES,
    CAD = CAD_Data,

    // ✅ LEFT JOIN using actual column names: Case Number (RMS) = ReportNumberNew (CAD)
    JoinedData = Table.Join(
        RMS, {"Case Number"},
        CAD, {"ReportNumberNew"},
        JoinKind.LeftOuter
    ),

    // ✅ Add flag for CAD data availability
    WithCADFlag = Table.AddColumn(JoinedData, "Has_CAD_DATA", each
        if [ReportNumberNew] <> null then "Yes" else "No", type text),

    // ✅ Select relevant columns for analysis
    FinalColumns = Table.SelectColumns(WithCADFlag, {
        "Case Number",
        "Incident_Date",
        "Incident_Time",
        "IncidentType",
        "ALL_INCIDENTS",
        "Crime_Category",
        "TimeOfDay",
        "Period",
        "Block",
        "Has_CAD_Data",
        "Time Spent",
        "Time Response",
        "CADNotes",
        "Officer of Record"
    })
in
    FinalColumns

    // 🕒 2025-07-23-06-00-00
// SCRPA_Time_v2/Actual_CAD_RMS_MCode_Solutions
// Author: R. A. Carucci
// Purpose: M Code solutions based on actual CAD and RMS export structures from your samples

// =============================================================================
// CAD EXPORT PROCESSING - Based on Your Actual Sample Data
// =============================================================================
// CAD Structure: Single "Incident" column with values like "Motor Vehicle Theft - 2C:20-3"
// Key Columns: ReportNumberNew, Incident, FullAddress2, PDZone, Grid, Time of Call, Officer, Disposition

// ALL_CRIMES_CAD Query (Master for CAD exports)
let
    Source = Excel.Workbook(File.Contents("C:\Users\carucci_r\OneDrive - City of Hackensack\_EXPORTS\_LawSoft_EXPORT\CAD\latest_cad_export.xlsx"), null, true),
    Data = Source{[Item="Sheet1", Kind="Sheet"]}[Data],
    PromotedHeaders = Table.PromoteHeaders(Data, [PromoteAllScalars=true]),
    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{}, "en-US"),

    // Remove excluded case (using correct CAD case number column)
    FilteredRows = Table.SelectRows(ChangedType, each ([ReportNumberNew] <> "25-057654")),

    // NO UNPIVOTING - CAD has single "Incident" column
    // Add case-insensitive crime categorization
    AddCrimeCategory = Table.AddColumn(FilteredRows, "Crime_Category", each
        let
            UpperIncident = Text.Upper([Incident] ?? "")
        in
            if Text.Contains(UpperIncident, "MOTOR VEHICLE THEFT") or Text.Contains(UpperIncident, "AUTO THEFT") or Text.Contains(UpperIncident, "MV THEFT") then "Motor Vehicle Theft"
            else if Text.Contains(UpperIncident, "BURGLARY") and (Text.Contains(UpperIncident, "AUTO") or Text.Contains(UpperIncident, "VEHICLE")) then "Burglary Auto"
            else if Text.Contains(UpperIncident, "BURGLARY") and Text.Contains(UpperIncident, "COMMERCIAL") then "Burglary Commercial"
            else if Text.Contains(UpperIncident, "BURGLARY") and Text.Contains(UpperIncident, "RESIDENCE") then "Burglary Residence"
            else if Text.Contains(UpperIncident, "ROBBERY") then "Robbery"
            else if Text.Contains(UpperIncident, "SEXUAL") then "Sexual Offenses"
            else "Other"
    ),

    // Add ArcGIS Pro compatible filtering (disposition = "See Report")
    FinalFiltered = Table.SelectRows(AddCrimeCategory, each
        Text.Contains(Text.Upper([Disposition] ?? ""), "SEE REPORT")
    ),

    // Add standardized fields for compatibility
    AddStandardFields = Table.AddColumn(FinalFiltered, "Case_Number", each [ReportNumberNew]),
    AddTimeField = Table.AddColumn(AddStandardFields, "Incident_DateTime", each [Time of Call]),
    AddAddressField = Table.AddColumn(AddTimeField, "Address", each [FullAddress2])
in
    AddAddressField

    let
    Source = ALL_CRIMES,
    // Simple filter that matches your Excel logic
    FilteredRows = Table.SelectRows(Source, each
        Text.Contains(Text.Upper([ALL_INCIDENTS] ?? ""), "SEXUAL", Comparer.OrdinalIgnoreCase) or
        Text.Contains(Text.Upper([ALL_INCIDENTS] ?? ""), "2C:14", Comparer.OrdinalIgnoreCase))
in
    FilteredRows

    // 🕒 2025-07-21-15-55-00
// Project: SCRPA_Analysis/Robbery_Query_Fixed_Cyclic
// Author: R. A. Carucci
// Purpose: Fixed Robbery query to prevent cyclic reference - references ALL_CRIMES not itself

let
    Source = ALL_CRIMES_CAD,
    Filtered = Table.SelectRows(Source, each [Crime_Category] = "Robbery")
in
    Filtered
    // 🕒 2025-07-21-15-34-00
    // Project: SCRPA_Analysis/Motor_Vehicle_Theft_Query
    // Author: R. A. Carucci
    // Purpose: Fixed Motor Vehicle Theft filter query - filters ALL_CRIMES for motor vehicle theft incidents using Crime_Category

    let
        Source = ALL_CRIMES_CAD,
        Filtered = Table.SelectRows(Source, each [Crime_Category] = "Motor Vehicle Theft")
    in
        Filtered

        // 🕒 2025-07-21-15-33-00
        // Project: SCRPA_Analysis/Burglary_Commercial_Residential_Query
        // Author: R. A. Carucci
        // Purpose: Fixed Commercial and Residential Burglary filter query - filters ALL_CRIMES for commercial and residential burglary incidents

        let
            Source = ALL_CRIMES_CAD,
            Filtered = Table.SelectRows(Source, each
                [Crime_Category] = "Burglary Commercial" or [Crime_Category] = "Burglary Residence"
            )
        in
            Filtered

            // 🕒 2025-07-21-15-32-00
            // Project: SCRPA_Analysis/Burglary_Auto_Query
            // Author: R. A. Carucci
            // Purpose: Fixed Burglary Auto filter query - filters ALL_CRIMES for auto burglary incidents
            let
                Source = ALL_CRIMES_CAD,
                Filtered = Table.SelectRows(Source, each [Crime_Category] = "Burglary Auto")
            in
                Filtered
