let
    Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\_LawSoft_EXPORT\RMS\EXPORT_RMS"),
    #"Filtered Hidden Files" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function" = Table.AddColumn(#"Filtered Hidden Files", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns" = Table.RenameColumns(#"Invoke Custom Function", {"Name", "Source.Name"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns", {"Source.Name", "Transform File"}),
    #"Expanded Table Column" = Table.ExpandTableColumn(#"Removed Other Columns", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    
    // Corrected data type transformations with proper null handling
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column",{
        {"Source.Name", type text}, 
        {"Case Number", type text}, 
        {"Incident Date", type date}, 
        {"Incident Time", type datetime}, 
        {"Incident Date_Between", type date}, 
        {"Incident Time_Between", type datetime}, 
        {"Report Date", type date}, 
        {"Report Time", type datetime}, 
        {"Incident Type_1", type text}, 
        {"Incident Type_2", type text}, 
        {"Incident Type_3", type text}, 
        {"FullAddress", type text}, 
        {"Grid", type text}, 
        {"Zone", Int64.Type}, 
        {"Narrative", type text}, 
        {"Total Value Stolen", Currency.Type}, 
        {"Total Value Recover", Currency.Type}, 
        {"Registration 1", type text}, 
        {"Make1", type text}, 
        {"Model1", type text}, 
        {"Reg State 1", type text}, 
        {"Registration 2", type text}, 
        {"Reg State 2", type text}, 
        {"Make2", type text}, 
        {"Model2", type text}, 
        {"Reviewed By", type text}, 
        {"CompleteCalc", type text}, 
        {"Officer of Record", type text}, 
        {"Squad", type text}, 
        {"Det_Assigned", type text}, 
        {"Case_Status", type text}, 
        {"NIBRS Classification", type text}
    }),
    
    #"Removed Source Column" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
    
    // Additional calculated columns for time analysis
    #"Added Custom Columns" = Table.AddColumn(#"Removed Source Column", "Start of Hour", 
        each if [Incident Time] <> null then Time.From(DateTime.Time([Incident Time])) else null, type time),
    #"Added INC_TIME" = Table.AddColumn(#"Added Custom Columns", "INC_TIME", 
        each if [Incident Time] <> null then Time.From(DateTime.Time([Incident Time])) else null, type time),
    #"Added INC_DATE" = Table.AddColumn(#"Added INC_TIME", "INC_DATE", 
        each if [Incident Date] <> null then Date.From([Incident Date]) else null, type date),
    #"Added INC_DATE_AND_TIME" = Table.AddColumn(#"Added INC_DATE", "INC_DATE_AND_TIME", 
        each if [Incident Date] <> null and [Incident Time] <> null 
             then DateTime.From([Incident Date]) + Duration.From([Incident Time]) 
             else null, type datetime),
    
    // Add derived date/time columns
    #"Added Date Components" = Table.AddColumn(#"Added INC_DATE_AND_TIME", "Day Name", 
        each if [INC_DATE] <> null then Date.DayOfWeekName([INC_DATE]) else null, type text),
    #"Added Month Name" = Table.AddColumn(#"Added Date Components", "Month Name", 
        each if [INC_DATE] <> null then Date.MonthName([INC_DATE]) else null, type text),
    #"Added Year" = Table.AddColumn(#"Added Month Name", "Year", 
        each if [INC_DATE] <> null then Date.Year([INC_DATE]) else null, Int64.Type),
    #"Added Week of Year" = Table.AddColumn(#"Added Year", "Week of Year", 
        each if [INC_DATE] <> null then Date.WeekOfYear([INC_DATE]) else null, Int64.Type),
    #"Added Day" = Table.AddColumn(#"Added Week of Year", "Day", 
        each if [INC_DATE] <> null then Date.Day([INC_DATE]) else null, Int64.Type),
    #"Added Day of Year" = Table.AddColumn(#"Added Day", "Day of Year", 
        each if [INC_DATE] <> null then Date.DayOfYear([INC_DATE]) else null, Int64.Type),
    
    // Filter for Commercial and Residence incidents (assuming ALL_INCIDENTS column exists)
    #"Filtered Incidents" = if Table.HasColumns(#"Added Day of Year", {"ALL_INCIDENTS"}) 
        then Table.SelectRows(#"Added Day of Year", each 
            [ALL_INCIDENTS] <> null and 
            (Text.Contains(Text.Upper([ALL_INCIDENTS]), "COMMERCIAL") or 
             Text.Contains(Text.Upper([ALL_INCIDENTS]), "RESIDENCE")))
        else #"Added Day of Year",
    
    // Remove duplicates based on Case Number
    #"Removed Duplicates" = Table.Distinct(#"Filtered Incidents", {"Case Number"}),
    
    // Apply final filters
    #"Final Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each 
        ([Incident Type_3] <> "Domestic Violence") and 
        ([Incident Type_1] <> "Violation of Court Order") and 
        ([Case Number] <> "25-021703")),
    
    // Reorder columns for better organization
    #"Reordered Columns" = Table.ReorderColumns(#"Final Filtered Rows", {
        "Case Number", "INC_DATE", "INC_TIME", "Start of Hour", "Day Name", "Month Name", 
        "Year", "Week of Year", "Day", "Day of Year", "INC_DATE_AND_TIME",
        "Incident Type_1", "Incident Type_2", "Incident Type_3", 
        "FullAddress", "Grid", "Zone", "Narrative", 
        "Total Value Stolen", "Total Value Recover",
        "Registration 1", "Make1", "Model1", "Reg State 1", 
        "Registration 2", "Reg State 2", "Make2", "Model2",
        "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", 
        "Det_Assigned", "Case_Status", "NIBRS Classification",
        "Incident Date", "Incident Time", "Incident Date_Between", 
        "Incident Time_Between", "Report Date", "Report Time"
    }),
    #"Trimmed Text" = Table.TransformColumns(#"Reordered Columns",{{"Narrative", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Narrative", Text.Clean, type text}})
in
    #"Cleaned Text"
