let
    Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\_LawSoft_EXPORT\RMS\EXPORT_RMS"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{
        {"Source.Name", type text}, {"Case Number", type text}, {"Incident Date", type date}, 
        {"Incident Time", type datetime}, {"Incident Date_Between", type date}, 
        {"Incident Time_Between", type datetime}, {"Report Date", type date}, 
        {"Report Time", type datetime}, {"Incident Type_1", type text}, 
        {"Incident Type_2", type text}, {"Incident Type_3", type text}, 
        {"FullAddress", type text}, {"Grid", type text}, {"Zone", Int64.Type}, 
        {"Narrative", type text}, {"Total Value Stolen", Currency.Type}, 
        {"Total Value Recover", Currency.Type}, {"Registration 1", type text}, 
        {"Make1", type text}, {"Model1", type text}, {"Reg State 1", type text}, 
        {"Registration 2", type text}, {"Reg State 2", type text}, 
        {"Make2", type text}, {"Model2", type text}, {"Reviewed By", type text}, 
        {"CompleteCalc", type text}, {"Officer of Record", type text}, 
        {"Squad", type text}, {"Det_Assigned", type text}, {"Case_Status", type text}, 
        {"NIBRS Classification", type text}
    }),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
    
    // Add all missing calculated columns
    #"Added INC_TIME" = Table.AddColumn(#"Removed Columns", "INC_TIME", 
        each if [Incident Time] <> null then Time.From(DateTime.Time([Incident Time])) else null, type time),
    #"Added INC_DATE" = Table.AddColumn(#"Added INC_TIME", "INC_DATE", 
        each if [Incident Date] <> null then Date.From([Incident Date]) else null, type date),
    #"Added Start of Hour" = Table.AddColumn(#"Added INC_DATE", "Start of Hour", 
        each if [INC_TIME] <> null then Time.From([INC_TIME]) else null, type time),
    #"Added INC_DATE_AND_TIME" = Table.AddColumn(#"Added Start of Hour", "INC_DATE_AND_TIME", 
        each if [Incident Date] <> null and [Incident Time] <> null 
             then DateTime.From([Incident Date]) + Duration.From([Incident Time]) 
             else null, type datetime),
    #"Added TOD" = Table.AddColumn(#"Added INC_DATE_AND_TIME", "TOD", 
        each if [INC_TIME] <> null then 
            if Time.Hour([INC_TIME]) >= 0 and Time.Hour([INC_TIME]) < 4 then "Early Morning (00:00–03:59)"
            else if Time.Hour([INC_TIME]) >= 4 and Time.Hour([INC_TIME]) < 8 then "Morning (04:00–07:59)"
            else if Time.Hour([INC_TIME]) >= 8 and Time.Hour([INC_TIME]) < 12 then "Morning Peak (08:00–11:59)"
            else if Time.Hour([INC_TIME]) >= 12 and Time.Hour([INC_TIME]) < 16 then "Afternoon (12:00–15:59)"
            else if Time.Hour([INC_TIME]) >= 16 and Time.Hour([INC_TIME]) < 20 then "Evening Peak (16:00–19:59)"
            else "Night (20:00–23:59)"
        else "Unknown", type text),
    #"Added Day Name" = Table.AddColumn(#"Added TOD", "Day Name", 
        each if [INC_DATE] <> null then Date.DayOfWeekName([INC_DATE]) else null, type text),
    #"Added Month Name" = Table.AddColumn(#"Added Day Name", "Month Name", 
        each if [INC_DATE] <> null then Date.MonthName([INC_DATE]) else null, type text),
    #"Added Year" = Table.AddColumn(#"Added Month Name", "Year", 
        each if [INC_DATE] <> null then Date.Year([INC_DATE]) else null, Int64.Type),
    #"Added Week of Year" = Table.AddColumn(#"Added Year", "Week of Year", 
        each if [INC_DATE] <> null then Date.WeekOfYear([INC_DATE]) else null, Int64.Type),
    #"Added Week of Month" = Table.AddColumn(#"Added Week of Year", "Week of Month", 
        each if [INC_DATE] <> null then Date.WeekOfMonth([INC_DATE]) else null, Int64.Type),
    #"Added Day" = Table.AddColumn(#"Added Week of Month", "Day", 
        each if [INC_DATE] <> null then Date.Day([INC_DATE]) else null, Int64.Type),
    #"Added Day of Year" = Table.AddColumn(#"Added Day", "Day of Year", 
        each if [INC_DATE] <> null then Date.DayOfYear([INC_DATE]) else null, Int64.Type),
    #"Added BLOCK" = Table.AddColumn(#"Added Day of Year", "BLOCK", 
        each if [FullAddress] <> null then Text.BeforeDelimiter([FullAddress], " ", 1) else null, type text),
    #"Added Location" = Table.AddColumn(#"Added BLOCK", "Location", 
        each [FullAddress], type text),
    #"Added ALL_INCIDENTS" = Table.AddColumn(#"Added Location", "ALL_INCIDENTS", 
        each [Incident Type_1] & (if [Incident Type_2] <> null then " - " & [Incident Type_2] else "") & 
             (if [Incident Type_3] <> null then " - " & [Incident Type_3] else ""), type text),
    #"Added CASE_NUMBER_LENGTH" = Table.AddColumn(#"Added ALL_INCIDENTS", "CASE_NUMBER_LENGTH", 
        each if [Case Number] <> null then Text.Length([Case Number]) else null, Int64.Type),
    #"Added St#" = Table.AddColumn(#"Added CASE_NUMBER_LENGTH", "St#", 
        each null, type text),
    #"Added Notes" = Table.AddColumn(#"Added St#", "Notes", 
        each null, type text),
    #"Added VEHICLE" = Table.AddColumn(#"Added Notes", "VEHICLE", 
        each if [Make1] <> null then [Make1] & " " & (if [Model1] <> null then [Model1] else "") else null, type text),
    #"Added Suspect" = Table.AddColumn(#"Added VEHICLE", "Suspect", 
        each null, type text),
    #"Added TOTAL_STOLEN_AMOUNT" = Table.AddColumn(#"Added Suspect", "TOTAL_STOLEN_AMOUNT", 
        each [Total Value Stolen], Currency.Type),
    #"Added REPORT_CYCLE" = Table.AddColumn(#"Added TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", 
        each null, type text),
    #"Added TIME_OF_DAY" = Table.AddColumn(#"Added REPORT_CYCLE", "TIME_OF_DAY", 
        each [TOD], type text),
    
    // Apply filters
    #"Filtered Rows" = Table.SelectRows(#"Added TIME_OF_DAY", each 
        [ALL_INCIDENTS] <> null and 
        (Text.Contains(Text.Upper([ALL_INCIDENTS]), "COMMERCIAL") or 
         Text.Contains(Text.Upper([ALL_INCIDENTS]), "RESIDENCE"))),
    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"Case Number"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates", each 
        ([Incident Type_3] <> "Domestic Violence") and 
        ([Incident Type_1] <> "Violation of Court Order") and 
        ([Case Number] <> "25-021703"))
in
    #"Filtered Rows1"
