let
    Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack\_LawSoft_EXPORT\RMS\EXPORT_RMS"),
    FilteredHiddenFiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    InvokedTransform = Table.AddColumn(FilteredHiddenFiles, "Transform File", each Transform_File([Content])),
    RenamedColumns1 = Table.RenameColumns(InvokedTransform, {"Name", "Source.Name"}),
    RemovedOtherColumns = Table.SelectColumns(RenamedColumns1, {"Source.Name", "Transform File"}),
    ExpandedTable = Table.ExpandTableColumn(RemovedOtherColumns, "Transform File", Table.ColumnNames(Transform_File(#"Sample File"))),
    FixedColumns = Table.RenameColumns(ExpandedTable, {
        {"CaseNumber", "Case Number"},
        {"IncDate", "Incident Date"},
        {"IncidentTime", "Incident Time"},
        {"IncidentDateBetween", "Incident Date_Between"},
        {"IncidentTimeBetween", "Incident Time_Between"},
        {"ReportDate", "Report Date"},
        {"ReportTime", "Report Time"},
        {"IncidentType1", "Incident Type_1"},
        {"IncidentType2", "Incident Type_2"},
        {"IncidentType3", "Incident Type_3"},
        {"TotalValueStolen", "Total Value Stolen"},
        {"TotalValueRecover", "Total Value Recover"},
        {"Registration1", "Registration 1"},
        {"RegState1", "Reg State 1"},
        {"Registration2", "Registration 2"},
        {"RegState2", "Reg State 2"},
        {"ReviewedBy", "Reviewed By"},
        {"OfficerOfRecord", "Officer of Record"}
    }),
    ChangedType = Table.TransformColumnTypes(FixedColumns,{
        {"Source.Name", type text},
        {"Case Number", type text},
        {"Incident Date", type date},
        {"Incident Time", type datetime},
        {"Incident Date_Between", type date},
        {"Incident Time_Between", type datetime},
        {"Report Date", type date},
        {"Report Time", type datetime},
        {"Incident Type_1", type text},
        {"Incident Type_2", type text},
        {"Incident Type_3", type text},
        {"FullAddress", type text},
        {"Grid", type text},
        {"Zone", Int64.Type},
        {"Narrative", type text},
        {"Total Value Stolen", Currency.Type},
        {"Total Value Recover", Currency.Type},
        {"Registration 1", type text},
        {"Make1", type text},
        {"Model1", type text},
        {"Reg State 1", type text},
        {"Registration 2", type text},
        {"Reg State 2", type text},
        {"Make2", type text},
        {"Model2", type text},
        {"Reviewed By", type text},
        {"CompleteCalc", type text},
        {"Officer of Record", type text},
        {"Squad", type text},
        {"Det_Assigned", type text},
        {"Case_Status", type text}
    }),
    TwentyEightDayStart = #date(2025, 3, 17),
    TwentyEightDayEnd = #date(2025, 4, 14),
    Filtered28Day = Table.SelectRows(ChangedType, each [Incident Date] >= TwentyEightDayStart and [Incident Date] <= TwentyEightDayEnd),
    Cleaned = Table.RemoveColumns(Filtered28Day,{"Source.Name"}),
    RemovedDuplicates = Table.Distinct(Cleaned, {"Case Number"}),
    SortedRows = Table.Sort(RemovedDuplicates, {{"Case Number", Order.Ascending}}),
    Result = SortedRows,
    #"Trimmed Text" = Table.TransformColumns(Result,{{"Narrative", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Narrative", Text.Clean, type text}})
in
    #"Cleaned Text"
